### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by miniflycn** [miniflycn/Q.iOS#1]
1. View -> view.json <= view.html + view.css (complied)
2. Component -> Swift & Lua (Hot Code)
3. Logic -> logic.js <= main.js (complied)

So, as a Font-end engineer, you just need to write view.html, view.css, and main.js：

``` html
<ViewController id="view">
    <UILabel class="myTitle" q-text="title">Hello world</UILabel>
    <UIButton class="myButton" q-on="click: change">Click Me</UIButton>
</ViewController>
```

``` css
.myTitle {
    color: green;
    margin: 40px 20px 0 20px;
}

.myButton {
    color: black;
    background-color: green;
    margin: 10px 20px 0 20px;
    heigtht: 20px;
}
```

``` js
new Q({
    id: '#view',
    data: {
        title: 'Hello world'
    },
    methods: {
        change: function () {
            this.$set('title', 'Hello IMWeb');
        }
    }
});
```
